### ISSUE TITLE
Archive or remove project

### ISSUE THREAD

**Issue by oskarb** [VISTALL/visual-studio-guids#1]
Please consider archiving or possibly even removing this repository in favour of the more recent migration:
https://github.com/JamesW75/visual-studio-project-type-guid

That one is also linked from the original code project page. It would simplify the search results on Google. :)

**Comment by VISTALL** [comment]
Hello. Sorry - but no. Reference account strange, due there no activities except two projects.

**Comment by oskarb** [comment]
Sure... the other one much longer though. Even has the very common C# .NET project type that's not in this repo.
